name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  pull-requests: read
  checks: read

jobs:
  release:
    uses: cpeter1207/rptadv-shared-library-workflows/.github/workflows/release.yml@main
    with:
      code_ref: ${{ github.sha }}
      tag: ${{ github.ref_name }}
      package_target: release-packages
